version: "3"
services:
  nodered:
    container_name: nodered1
    image: nodered/node-red:latest
    ports:
      - "1881:1880"  
    restart: unless-stopped

    container_name: nodered2
    image: nodered/node-red:latest
    ports:
      - "1882:1880"  
    restart: unless-stopped
    networks:
      faradaynet:
        ipv4_address: 192.168.93.3
networks:
  faradaynet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.93.0/24"
        
     
